### ISSUE TITLE
FindFlix 1.0.3.2 finds nothing, and there's no list of categories 

### ISSUE THREAD

**Issue by grahamperrin** [Jarker/FindFlix#1]
Waterfox 56.2.0.7 (57.2.0 build 20180515213058) on FreeBSD-CURRENT: 

![2018-05-20 03 58 34 waterfox](https://user-images.githubusercontent.com/192271/40275240-7f342856-5be2-11e8-97a3-3910896a64cf.png)

There's the same issue with: 

- FindFlix alone enabled with Waterfox
- FindFlix with Firefox 60.0.1 (64-bit).

**Comment by Jarker** [comment]
FindFlix is for searching categories, programs and films aren't indexed.
This may be linked to the FireFox version which I have no control over, however, as it was ported by somebody else.

**Comment by grahamperrin** [comment]
Ah, OK! Sorry. Without zooming in on the screenshot, I couldn't see that text had been typed. 

Now I see the hint, 

> Type to begin searching…

I didn't see it originally because I _imagined_ this workflow: 

1. the extension primarily changes how the categories appear in the Netflix window, i.e. a much longer page with umpteen categories
2. user selects a category
3. then use the pop-up to seek a film in that category. 

My misunderstanding! 

Close this if you like. 

Thanks
