### ISSUE TITLE
Home page kiwy.io - Registered at Namecheap.com

### ISSUE THREAD

**Issue by grahamperrin** [Jarker/FindFlix#2]
The home icon refers to http://www.findflix.kiwy.io/ with nothing related to FindFlix: 

![2018-05-20 04 06 24 kiwy io](https://user-images.githubusercontent.com/192271/40275291-5f582cb6-5be3-11e8-942a-5d21bde97e63.png)

>  2018 Copyright. All Rights Reserved.
> 
> The Sponsored Listings displayed above are served automatically by a third party. Neither Parkingcrew nor the domain owner maintain any relationship with the advertisers.
> 
> Privacy Policy

**Comment by Jarker** [comment]
This domain has recently expired. I'm unsure as to whether I will be relaunching FindFlix on another domain, though I may create a GitHub Pages for it.
When I do, the extension will be updated with a working link.

**Comment by Jarker** [comment]
FYI - The web app is now live at https://joshbarker.me/findflix/

**Comment by grahamperrin** [comment]
Thanks!
